spring.application.name=SocialMedia

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/social_media?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=shutup:p
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=4a8f3c2e1b7d6a9f0e5c4b3d2a1f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f
jwt.expiration-ms=86400000
